#+title: Quiet Walking Dev Notes

* Sensor Model

Simulating individual phonons is unusably slow with Hoot. I'll need something higher level instead. So let's say I've got a "sonar ping" notion which has a radius and 1000(?) sample points. Whenever the ping sweeps past an object, that ping gets sent back home and the samples overlapping that object's bounding circle get removed.

* Goals

"Sink the enemy base", maybe: you're given a position for a defended base and you need to get in and sink it

* Research

Speed of sound in water: 0.81 NM/sec

* Notes

In-game units are nautical miles and seconds

Object structure:
- <entity>
  - <rock>
  - <player>
  - <enemy>
  - <base>

* Name

"Quiet Walking" is one, though the movie isn't actually about submarines. Consider: "The Hunt for Mauve July"

* Log

Next steps:
- make a "rock" to ping sonar off

I'm missing something about how paths in canvas work. right now filling an ellipse only works if I double-draw it, which is super weird.
- Nope, it wasn't canvas, it was something fucky with (ellipse)'s argument types!

  (ellipse context 100 100 50 75 (/ %pi 4) 0 (* 2 %pi) 0)
  becomes
  Ellipse 4.94e-322 4.94e-322 2.47e-322 3.7e-322 0.7853981633974483 0 6.283185307179586 0

  which I'm assuming is a miscompile. Lesson learned for now, ensure I'm passing floats to extern calls that need floats.
